// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppError, AppResult, AppResultPage};
use crate::common::result::{ok_result, ok_result_data, ok_result_page};
use crate::model::system::sys_operate_log_model::OperateLog;
use crate::vo::system::sys_operate_log_vo::*;
use crate::RB;
use rbatis::PageRequest;
use rbs::value;

pub struct OperateLogService;

impl OperateLogService {
    /*
     *删除操作日志记录
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */
    pub async fn delete_sys_operate_log(item: DeleteOperateLogReq) -> AppResult<String> {
        let rb = &mut RB.clone();

        OperateLog::delete_by_map(rb, value! {"id": & item.ids}).await.map(|_| ok_result())?
    }

    /*
     *查询操作日志记录详情
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */
    pub async fn query_sys_operate_log_detail(item: QueryOperateLogDetailReq) -> AppResult<OperateLogResp> {
        OperateLog::select_by_id(&mut RB.clone(), &item.id)
            .await?
            .map_or_else(|| Err(AppError::BusinessError("操作日志不存在")), |x| ok_result_data(x.into()))
    }

    /*
     *查询操作日志记录列表
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */
    pub async fn query_sys_operate_log_list(item: QueryOperateLogListReq) -> AppResultPage<Vec<OperateLogResp>> {
        let rb = &mut RB.clone();

        OperateLog::select_by_page(rb, &PageRequest::from(&item), &item)
            .await
            .map(|x| ok_result_page(x.records.into_iter().map(|x| x.into()).collect::<Vec<OperateLogResp>>(), x.total))?
    }
}
