// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppError, AppResult};
use crate::common::result::{ok_result_data, ok_result_page};
use crate::model::system::sys_login_log_model::LoginLog;
use crate::vo::system::sys_login_log_vo::*;
use crate::RB;
use rbatis::plugin::page::PageRequest;
use rbs::value;
use salvo::Response;

pub struct LoginLogService;

impl LoginLogService {
    /*
     *删除系统访问记录
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */
    pub async fn delete_sys_login_log(item: DeleteLoginLogReq, res: &mut Response) -> AppResult {
        let rb = &mut RB.clone();

        LoginLog::delete_by_map(rb, value! {"id": &item.ids}).await.map(|x| ok_result_data(res, x))?
    }

    /*
     *查询系统访问记录详情
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */
    pub async fn query_sys_login_log_detail(item: QueryLoginLogDetailReq, res: &mut Response) -> AppResult {
        log::info!("query sys_login_log_detail params: {:?}", &item);

        LoginLog::select_by_id(&mut RB.clone(), &item.id).await?.map_or_else(
            || Err(AppError::BusinessError("系统访问记录不存在")),
            |x| {
                let data: LoginLogResp = x.into();
                ok_result_data(res, data)
            },
        )
    }

    /*
     *查询系统访问记录列表
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */
    pub async fn query_sys_login_log_list(item: QueryLoginLogListReq, res: &mut Response) -> AppResult {
        log::info!("query sys_login_log_list params: {:?}", &item);

        let rb = &mut RB.clone();

        LoginLog::select_by_page(rb, &PageRequest::from(&item), &item)
            .await
            .map(|x| ok_result_page(res, x.records.into_iter().map(|x| x.into()).collect::<Vec<LoginLogResp>>(), x.total))?
    }
}
