// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppError, AppResult, AppResultPage};
use crate::common::result::{ok_result, ok_result_data, ok_result_page};
use crate::model::system::sys_post_model::Post;
use crate::model::system::sys_user_post_model::UserPost;
use crate::vo::system::sys_post_vo::*;
use crate::RB;
use rbatis::plugin::page::PageRequest;
use rbatis::rbdc::DateTime;
use rbs::value;

pub struct PostService;

impl PostService {
    /*
     *添加岗位信息
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */

    pub async fn add_sys_post(mut item: PostReq) -> AppResult<String> {
        let rb = &mut RB.clone();

        if Post::select_by_map(rb, value! {"post_name": &item.post_name}).await?.len() > 0 {
            return Err(AppError::BusinessError("岗位名称已存在"));
        }

        if Post::select_by_map(rb, value! {"post_code": &item.post_code}).await?.len() > 0 {
            return Err(AppError::BusinessError("岗位编码已存在"));
        }

        item.id = None;
        Post::insert(rb, &Post::from(item)).await.map(|_| ok_result())?
    }

    /*
     *删除岗位信息
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */

    pub async fn delete_sys_post(item: DeletePostReq) -> AppResult<String> {
        let rb = &mut RB.clone();

        let ids = item.ids;
        for id in &ids {
            match Post::select_by_id(rb, id).await? {
                None => return Err(AppError::BusinessError("不能删除")),
                Some(_) => {
                    if UserPost::count_user_post_by_id(rb, id).await? > 0 {
                        return Err(AppError::BusinessError("已分配,不能删除"));
                    }
                }
            };
        }

        Post::delete_by_map(rb, value! {"id": ids}).await.map(|_| ok_result())?
    }

    /*
     *更新岗位信息
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */

    pub async fn update_sys_post(item: PostReq) -> AppResult<String> {
        let rb = &mut RB.clone();

        let id = item.id;

        if id.is_none() {
            return Err(AppError::BusinessError("主键不能为空"));
        }
        if Post::select_by_id(rb, &id.unwrap_or_default()).await?.is_none() {
            return Err(AppError::BusinessError("岗位不存在"));
        }

        if Post::select_by_map(rb, value! {"post_name": &item.post_name, "id !=": id}).await?.len() > 0 {
            return Err(AppError::BusinessError("岗位名称已存在"));
        }

        if Post::select_by_map(rb, value! {"post_code": &item.post_code, "id !=": id}).await?.len() > 0 {
            return Err(AppError::BusinessError("岗位编码已存在"));
        }

        Post::update_by_map(rb, &Post::from(item), value! {"id": id}).await.map(|_| ok_result())?
    }

    /*
     *更新岗位信息状态
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */

    pub async fn update_sys_post_status(item: UpdatePostStatusReq) -> AppResult<String> {
        let update_sql = format!(
            "update sys_post set status = ? ,update_time = ? where id in ({})",
            item.ids.iter().map(|_| "?").collect::<Vec<&str>>().join(", ")
        );

        let mut param = vec![value!(item.status), value!(DateTime::now())];
        param.extend(item.ids.iter().map(|&id| value!(id)));

        RB.clone().exec(&update_sql, param).await.map(|_| ok_result())?
    }

    /*
     *查询岗位信息详情
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */

    pub async fn query_sys_post_detail(item: QueryPostDetailReq) -> AppResult<PostResp> {
        Post::select_by_id(&mut RB.clone(), &item.id)
            .await?
            .map_or_else(|| Err(AppError::BusinessError("岗位不存在")), |x| ok_result_data(x.into()))
    }

    /*
     *查询岗位信息列表
     *author：刘飞华
     *date：2025/01/08 13:51:14
     */

    pub async fn query_sys_post_list(item: QueryPostListReq) -> AppResultPage<PostResp> {
        let rb = &mut RB.clone();

        Post::select_by_page(rb, &PageRequest::from(&item), &item)
            .await
            .map(|x| ok_result_page(x.records.into_iter().map(|x| x.into()).collect::<Vec<PostResp>>(), x.total))?
    }
}
