// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppResult, AppResultPage};
use crate::service::system::sys_dict_type_service::DictTypeService;
use crate::vo::system::sys_dict_type_vo::*;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
/*
 *添加字典类型
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_dict_type(req: JsonBody<DictTypeReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("add sys_dict_type params: {:?}", &item);

    DictTypeService::add_sys_dict_type(item).await
}

/*
 *删除字典类型
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_dict_type(req: JsonBody<DeleteDictTypeReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("delete sys_dict_type params: {:?}", &item);

    DictTypeService::delete_sys_dict_type(item).await
}

/*
 *更新字典类型
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_dict_type(req: JsonBody<DictTypeReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_dict_type params: {:?}", &item);

    DictTypeService::update_sys_dict_type(item).await
}

/*
 *更新字典类型状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_dict_type_status(req: JsonBody<UpdateDictTypeStatusReq>) -> AppResult<String> {
    let item = req.into_inner();

    DictTypeService::update_sys_dict_type_status(item).await
}

/*
 *查询字典类型详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_dict_type_detail(req: JsonBody<QueryDictTypeDetailReq>) -> AppResult<DictTypeResp> {
    let item = req.into_inner();

    DictTypeService::query_sys_dict_type_detail(item).await
}

/*
 *查询字典类型列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_dict_type_list(req: JsonBody<QueryDictTypeListReq>) -> AppResultPage<Vec<DictTypeResp>> {
    let item = req.into_inner();

    DictTypeService::query_sys_dict_type_list(item).await
}
