// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppError, AppResult};
use crate::common::result::{ok_result, ok_result_data, ok_result_page};
use crate::model::system::sys_menu_model::{select_count_menu_by_parent_id, Menu};
use crate::model::system::sys_role_menu_model::RoleMenu;
use crate::vo::system::sys_menu_vo::*;
use crate::RB;
use rbatis::plugin::page::PageRequest;
use rbatis::rbdc::DateTime;
use rbs::value;
use salvo::prelude::*;
use salvo::{Request, Response};
/*
 *添加菜单信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_menu(req: &mut Request, res: &mut Response) -> AppResult {
    let mut item = req.parse_json::<MenuReq>().await?;
    log::info!("add sys_menu params: {:?}", &item);

    let rb = &mut RB.clone();
    if Menu::select_by_map(rb, value! {"menu_name": &item.menu_name}).await?.len() > 0 {
        return Err(AppError::BusinessError("菜单名称已存在"));
    }

    if let Some(url) = item.menu_url.clone() {
        if url != "".to_string() {
            if Menu::select_by_map(rb, value! {"menu_url": url}).await?.len() > 0 {
                return Err(AppError::BusinessError("路由路径已存在"));
            }
        }
    }

    item.id = None;
    Menu::insert(rb, &Menu::from(item)).await.map(|_| ok_result(res))?
}

/*
 *删除菜单信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_menu(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<DeleteMenuReq>().await?;
    log::info!("delete sys_menu params: {:?}", &item);

    let rb = &mut RB.clone();

    let ids = item.ids;
    for x in ids.clone() {
        if select_count_menu_by_parent_id(rb, &x).await? > 0 {
            return Err(AppError::BusinessError("存在子菜单,不允许删除"));
        }

        if RoleMenu::select_count_menu_by_menu_id(rb, &x).await? > 0 {
            return Err(AppError::BusinessError("菜单已分配,不允许删除"));
        }
    }

    Menu::delete_by_map(rb, value! {"id": &ids}).await.map(|_| ok_result(res))?
}

/*
 *更新菜单信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_menu(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<MenuReq>().await?;
    log::info!("update sys_menu params: {:?}", &item);

    let rb = &mut RB.clone();

    let id = item.id;

    if id.is_none() {
        return Err(AppError::BusinessError("主键不能为空"));
    }

    if Menu::select_by_id(rb, &id.unwrap_or_default()).await?.is_none() {
        return Err(AppError::BusinessError("菜单信息不存在"));
    }

    let rb = &mut RB.clone();
    if Menu::select_by_map(rb, value! {"menu_name": &item.menu_name, "id!=": &id}).await?.len() > 0 {
        return Err(AppError::BusinessError("菜单名称已存在"));
    }

    if let Some(url) = item.menu_url.clone() {
        if url != "".to_string() {
            if Menu::select_by_map(rb, value! {"menu_url": url, "id!=": &id}).await?.len() > 0 {
                return Err(AppError::BusinessError("路由路径已存在"));
            }
        }
    }

    Menu::update_by_map(rb, &Menu::from(item), value! {"id": &id}).await.map(|_| ok_result(res))?
}

/*
 *更新菜单信息状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_menu_status(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<UpdateMenuStatusReq>().await?;

    log::info!("update sys_menu_status params: {:?}", &item);

    let update_sql = format!(
        "update sys_menu set status = ? ,update_time = ? where id in ({})",
        item.ids.iter().map(|_| "?").collect::<Vec<&str>>().join(", ")
    );

    let mut param = vec![value!(item.status), value!(DateTime::now())];
    param.extend(item.ids.iter().map(|&id| value!(id)));

    RB.clone().exec(&update_sql, param).await.map(|_| ok_result(res))?
}

/*
 *查询菜单信息详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_menu_detail(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<QueryMenuDetailReq>().await?;
    log::info!("query sys_menu_detail params: {:?}", &item);

    Menu::select_by_id(&mut RB.clone(), &item.id).await?.map_or_else(
        || Err(AppError::BusinessError("菜单信息不存在")),
        |x| {
            let data: MenuResp = x.into();
            ok_result_data(res, data)
        },
    )
}

/*
 *查询菜单信息列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_menu_list(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<QueryMenuListReq>().await?;
    log::info!("query sys_menu_list params: {:?}", &item);
    
    Menu::select_by_map(&mut RB.clone(), value! {})
        .await
        .map(|x| ok_result_data(res, x.into_iter().map(|x| x.into()).collect::<Vec<MenuResp>>()))?
}

/*
 *查询菜单信息(排除按钮)
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_menu_list_simple(res: &mut Response) -> AppResult {
    Menu::select_by_map(&mut RB.clone(), value! {"menu_type!=": 3, "status": 1})
        .await
        .map(|x| ok_result_data(res, x.into_iter().map(|x| MenuSimpleResp::from(x)).collect::<Vec<MenuSimpleResp>>()))?
}

/*
 *查询菜单信息列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_menu_resource_list(req: &mut Request, res: &mut Response) -> AppResult {
    let req = req.parse_json::<QueryMenuListReq>().await?;
    log::info!("query sys_menu_list params: {:?}", &req);

    let rb = &mut RB.clone();
    let item = &req;

    Menu::select_by_page(rb, &PageRequest::from(item), item)
        .await
        .map(|x| ok_result_page(res, x.records.into_iter().map(|x| x.into()).collect::<Vec<MenuResp>>(), x.total))?
}
