// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppResult, AppResultPage};
use crate::service::system::sys_notice_service::NoticeService;
use crate::vo::system::sys_notice_vo::*;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
use tracing::info;
/*
 *添加通知公告
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_notice(req: JsonBody<NoticeReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("add sys_notice params: {:?}", &item);

    NoticeService::add_sys_notice(item).await
}

/*
 *删除通知公告
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_notice(req: JsonBody<DeleteNoticeReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("delete sys_notice params: {:?}", &item);

    NoticeService::delete_sys_notice(item).await
}

/*
 *更新通知公告
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_notice(req: JsonBody<NoticeReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("update sys_notice params: {:?}", &item);

    NoticeService::update_sys_notice(item).await
}

/*
 *更新通知公告状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_notice_status(req: JsonBody<UpdateNoticeStatusReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("update sys_notice_status params: {:?}", &item);

    NoticeService::update_sys_notice_status(item).await
}

/*
 *查询通知公告详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_notice_detail(req: JsonBody<QueryNoticeDetailReq>) -> AppResult<NoticeResp> {
    let item = req.into_inner();
    info!("query sys_notice_detail params: {:?}", &item);

    NoticeService::query_sys_notice_detail(item).await
}

/*
 *查询通知公告列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_notice_list(req: JsonBody<QueryNoticeListReq>) -> AppResultPage<NoticeResp> {
    let item = req.into_inner();
    info!("query sys_notice_list params: {:?}", &item);

    NoticeService::query_sys_notice_list(item).await
}
