// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppResult, AppResultPage};
use crate::vo::system::sys_user_vo::*;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
use crate::service::system::sys_user_service::UserService;
/*
 *添加用户信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_user(req: JsonBody<UserReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("add sys_user params: {:?}", &item);

    UserService::add_sys_user(item).await
}

/*
 *删除用户信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_user(depot: &mut Depot, req: JsonBody<DeleteUserReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("delete sys_user params: {:?}", &item);

    UserService::delete_sys_user(depot, item).await
}

/*
 *更新用户信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_user(req: JsonBody<UserReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_user params: {:?}", &item);

    UserService::update_sys_user(item).await
}

/*
 *更新用户信息状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_user_status(req: JsonBody<UpdateUserStatusReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_user_status params: {:?}", &item);

    UserService::update_sys_user_status(item).await
}

/*
 *重置用户密码
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn reset_sys_user_password(req: JsonBody<ResetUserPwdReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_user_password params: {:?}", &item);

    UserService::reset_sys_user_password(item).await
}

/*
 *用户修改自己的密码
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_user_password(req: JsonBody<UpdateUserPwdReq>, depot: &mut Depot) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_user_password params: {:?}", &item);

    UserService::update_sys_user_password(item, depot).await
}

/*
 *查询用户信息详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_user_detail(req: JsonBody<QueryUserDetailReq>) -> AppResult<UserResp> {
    let item = req.into_inner();
    log::info!("query sys_user_detail params: {:?}", &item);

    UserService::query_sys_user_detail(item).await
}

/*
 *查询用户信息列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_user_list(req: JsonBody<QueryUserListReq>) -> AppResultPage<UserResp> {
    let item = req.into_inner();
    log::info!("query sys_user_list params: {:?}", &item);

    UserService::query_sys_user_list(item).await
}

/*
 *用户登录
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn login(depot: &mut Depot, req: &mut Request) -> AppResult<String> {
    UserService::login(depot, req).await
}

/*
 *查询用户角色
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_user_role(req: JsonBody<QueryUserRoleReq>) -> AppResult<QueryUserRoleResp> {
    let item = req.into_inner();
    log::info!("query_user_role params: {:?}", item);

    UserService::query_user_role(item).await
}

/*
 *更新用户与角色的关联
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_user_role(req: JsonBody<UpdateUserRoleReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update_user_role params: {:?}", item);

    UserService::update_user_role(item).await
}

/*
 *查询用户菜单
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_user_menu(depot: &mut Depot) -> AppResult<QueryUserMenuResp> {
    let user_id = depot.get::<i64>("userId").copied().unwrap();
    let user_name = depot.get::<String>("username").unwrap();
    log::info!("query user menu params user_id {:?}", user_id);
    log::info!("query user menu params user_name {:?}", user_name);

    UserService::query_user_menu(user_id).await
}
