// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::AppResult;
use crate::service::system::sys_login_log_service::LoginLogService;
use crate::vo::system::sys_login_log_vo::*;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
use salvo::Response;
/*
 *删除系统访问记录
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_login_log(req: JsonBody<DeleteLoginLogReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("delete sys_login_log params: {:?}", &item);

    LoginLogService::delete_sys_login_log(item, res).await
}

/*
 *查询系统访问记录详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_login_log_detail(req: JsonBody<QueryLoginLogDetailReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("query sys_login_log_detail params: {:?}", &item);

    LoginLogService::query_sys_login_log_detail(item, res).await
}

/*
 *查询系统访问记录列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_login_log_list(req: JsonBody<QueryLoginLogListReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("query sys_login_log_list params: {:?}", &item);

    LoginLogService::query_sys_login_log_list(item, res).await
}
