// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::AppResult;
use crate::service::system::sys_notice_sevice::NoticeService;
use crate::vo::system::sys_notice_vo::*;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
use salvo::Response;
/*
 *添加通知公告
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_notice(req: JsonBody<NoticeReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("add sys_notice params: {:?}", &item);

    NoticeService::add_sys_notice(item, res).await
}

/*
 *删除通知公告
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_notice(req: JsonBody<DeleteNoticeReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("delete sys_notice params: {:?}", &item);

    NoticeService::delete_sys_notice(item, res).await
}

/*
 *更新通知公告
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_notice(req: JsonBody<NoticeReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("update sys_notice params: {:?}", &item);

    NoticeService::update_sys_notice(item, res).await
}

/*
 *更新通知公告状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_notice_status(req: JsonBody<UpdateNoticeStatusReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("update sys_notice_status params: {:?}", &item);

    NoticeService::update_sys_notice_status(item, res).await
}

/*
 *查询通知公告详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_notice_detail(req: JsonBody<QueryNoticeDetailReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("query sys_notice_detail params: {:?}", &item);

    NoticeService::query_sys_notice_detail(item, res).await
}

/*
 *查询通知公告列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_notice_list(req: JsonBody<QueryNoticeListReq>, res: &mut Response) -> AppResult {
    let item = req.into_inner();
    log::info!("query sys_notice_list params: {:?}", &item);

    NoticeService::query_sys_notice_list(item, res).await
}
