// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppResult, AppResultPage};
use crate::service::system::sys_post_service::PostService;
use crate::vo::system::sys_post_vo::*;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
/*
 *添加岗位信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_post(req: JsonBody<PostReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("add sys_post params: {:?}", &item);

    PostService::add_sys_post(item).await
}

/*
 *删除岗位信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_post(req: JsonBody<DeletePostReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("delete sys_post params: {:?}", &item);

    PostService::delete_sys_post(item).await
}

/*
 *更新岗位信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_post(req: JsonBody<PostReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_post params: {:?}", &item);

    PostService::update_sys_post(item).await
}

/*
 *更新岗位信息状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_post_status(req: JsonBody<UpdatePostStatusReq>) -> AppResult<String> {
    let item = req.into_inner();
    log::info!("update sys_post_status params: {:?}", &item);

    PostService::update_sys_post_status(item).await
}

/*
 *查询岗位信息详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_post_detail(req: JsonBody<QueryPostDetailReq>) -> AppResult<PostResp> {
    let item = req.into_inner();
    log::info!("query sys_post_detail params: {:?}", &item);

    PostService::query_sys_post_detail(item).await
}

/*
 *查询岗位信息列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_post_list(req: JsonBody<QueryPostListReq>) -> AppResultPage<PostResp> {
    let item = req.into_inner();
    log::info!("query sys_post_list params: {:?}", &item);

    PostService::query_sys_post_list(item).await
}
