// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppError, AppResult};
use crate::common::result::{ok_result, ok_result_data, ok_result_page};
use crate::model::system::sys_dict_data_model::DictData;
use crate::vo::system::sys_dict_data_vo::*;
use crate::RB;
use rbatis::plugin::page::PageRequest;
use rbatis::rbdc::DateTime;
use rbs::value;
use salvo::prelude::*;
use salvo::{Request, Response};

/*
 *添加字典数据
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_dict_data(req: &mut Request, res: &mut Response) -> AppResult {
    let mut item = req.parse_json::<DictDataReq>().await?;

    log::info!("add sys_dict_data params: {:?}", &item);

    let rb = &mut RB.clone();
    if DictData::select_by_dict_label(rb, &item.dict_type, &item.dict_label).await?.is_some() {
        return Err(AppError::BusinessError("字典标签已存在"));
    }

    if DictData::select_by_dict_value(rb, &item.dict_type, &item.dict_value).await?.is_some() {
        return Err(AppError::BusinessError("字典键值已存在"));
    }

    item.id = None;
    DictData::insert(rb, &DictData::from(item)).await.map(|_| ok_result(res))?
}

/*
 *删除字典数据
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_dict_data(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<DeleteDictDataReq>().await?;
    log::info!("delete sys_dict_data params: {:?}", &item);

    let rb = &mut RB.clone();

    DictData::delete_by_map(rb, value! {"id": &item.ids}).await.map(|_| ok_result(res))?
}

/*
 *更新字典数据
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_dict_data(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<DictDataReq>().await?;
    log::info!("update sys_dict_data params: {:?}", &item);

    let rb = &mut RB.clone();

    let id = item.id;
    if id.is_none() {
        return Err(AppError::BusinessError("主键不能为空"));
    }
    if DictData::select_by_id(rb, &id.unwrap_or_default()).await?.is_none() {
        return Err(AppError::BusinessError("字典数据不存在"));
    }

    if let Some(x) = DictData::select_by_dict_label(rb, &item.dict_type, &item.dict_label).await? {
        if x.id != id {
            return Err(AppError::BusinessError("字典标签已存在"));
        }
    }

    if let Some(x) = DictData::select_by_dict_value(rb, &item.dict_type, &item.dict_value).await? {
        if x.id != id {
            return Err(AppError::BusinessError("字典键值已存在"));
        }
    }

    DictData::update_by_map(rb, &DictData::from(item), value! {"id": &id}).await.map(|_| ok_result(res))?
}

/*
 *更新字典数据状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_dict_data_status(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<UpdateDictDataStatusReq>().await?;
    log::info!("update sys_dict_data_status params: {:?}", &item);

    let update_sql = format!(
        "update sys_dict_data set status = ? ,update_time = ? where id in ({})",
        item.ids.iter().map(|_| "?").collect::<Vec<&str>>().join(", ")
    );

    let mut param = vec![value!(item.status), value!(DateTime::now())];
    param.extend(item.ids.iter().map(|&id| value!(id)));

    RB.clone().exec(&update_sql, param).await.map(|_| ok_result(res))?
}

/*
 *查询字典数据详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_dict_data_detail(req: &mut Request, res: &mut Response) -> AppResult {
    let item = req.parse_json::<QueryDictDataDetailReq>().await?;
    log::info!("query sys_dict_data_detail params: {:?}", &item);

    DictData::select_by_id(&mut RB.clone(), &item.id).await?.map_or_else(
        || Err(AppError::BusinessError("字典数据不存在")),
        |x| {
            let data: DictDataResp = x.into();
            ok_result_data(res, data)
        },
    )
}

/*
 *查询字典数据列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_dict_data_list(req: &mut Request, res: &mut Response) -> AppResult {
    let req = req.parse_json::<QueryDictDataListReq>().await?;
    log::info!("query sys_dict_data_list params: {:?}", &req);

    let rb = &mut RB.clone();
    let item = &req;

    DictData::select_dict_data_list(rb, &PageRequest::from(item), item)
        .await
        .map(|x| ok_result_page(res, x.records.into_iter().map(|x| x.into()).collect::<Vec<DictDataResp>>(), x.total))?
}
