// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppError, AppResult};
use crate::common::result::{ok_result, ok_result_data, ok_result_page};
use crate::model::system::sys_dept_model::Dept;
use crate::model::system::sys_login_log_model::LoginLog;
use crate::model::system::sys_menu_model::Menu;
use crate::model::system::sys_role_model::Role;
use crate::model::system::sys_user_model::User;
use crate::model::system::sys_user_post_model::UserPost;
use crate::model::system::sys_user_role_model::{is_admin, UserRole};
use crate::utils::jwt_util::JwtToken;
use crate::utils::user_agent_util::UserAgentUtil;
use crate::vo::system::sys_dept_vo::DeptResp;
use crate::vo::system::sys_role_vo::RoleResp;
use crate::vo::system::sys_user_vo::*;
use crate::RB;
use chrono::Local;
use rbatis::plugin::page::PageRequest;
use rbatis::rbatis_codegen::ops::AsProxy;
use rbatis::rbdc::datetime::DateTime;
use rbs::value;
use salvo::prelude::*;
use salvo::{Request, Response};
use std::collections::{HashMap, HashSet};
/*
 *添加用户信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_user(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let mut item = req.parse_json::<UserReq>().await?;
    log::info!("add sys_user params: {:?}", &item);

    let rb = &mut RB.clone();
    if User::select_by_user_name(rb, &item.user_name).await?.is_some() {
        return Err(AppError::BusinessError("登录账号已存在"));
    }

    if User::select_by_mobile(rb, &item.mobile).await?.is_some() {
        return Err(AppError::BusinessError("手机号码已存在"));
    }

    if User::select_by_email(rb, &item.email).await?.is_some() {
        return Err(AppError::BusinessError("邮箱账号已存在"));
    }

    let post_ids = item.post_ids.clone();
    item.id = None;
    let id = User::insert(rb, &User::from(item)).await?.last_insert_id;

    let mut user_post_list: Vec<UserPost> = Vec::new();
    for post_id in post_ids {
        user_post_list.push(UserPost { user_id: id.i64(), post_id })
    }

    let size = user_post_list.len() as u64;
    UserPost::insert_batch(rb, &user_post_list, size).await.map(|_| ok_result(res))?
}

/*
 *删除用户信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_user(depot: &mut Depot, req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<DeleteUserReq>().await?;
    log::info!("delete sys_user params: {:?}", &item);

    if let Ok(user_id) = depot.get::<i64>("userId").copied() {
        let ids = item.ids.clone();
        if ids.contains(&user_id) {
            return Err(AppError::BusinessError("当前用户不能删除"));
        }
        if ids.contains(&1) {
            return Err(AppError::BusinessError("不允许操作超级管理员用户"));
        }

        let rb = &mut RB.clone();
        UserRole::delete_by_map(rb, value! {"user_id": &ids}).await?;

        UserPost::delete_by_map(rb, value! {"user_id": &ids}).await?;

        User::delete_by_map(rb, value! {"id": &item.ids}).await.map(|_| ok_result(res))?
    } else {
        Err(AppError::BusinessError("参数错误"))
    }
}

/*
 *更新用户信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_user(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<UserReq>().await?;
    log::info!("update sys_user params: {:?}", &item);

    let id = item.id;
    if id.is_none() {
        return Err(AppError::BusinessError("主键不能为空"));
    }
    if id == Some(1) {
        return Err(AppError::BusinessError("不允许操作超级管理员用户"));
    }

    let rb = &mut RB.clone();
    let user = match User::select_by_id(rb, item.id.unwrap_or_default()).await? {
        None => return Err(AppError::BusinessError("用户不存在")),
        Some(x) => x,
    };

    if let Some(x) = User::select_by_user_name(rb, &item.user_name).await? {
        if x.id != id {
            return Err(AppError::BusinessError("登录账号已存在"));
        }
    }

    if let Some(x) = User::select_by_mobile(rb, &item.mobile).await? {
        if x.id != id {
            return Err(AppError::BusinessError("手机号码已存在"));
        }
    }

    if let Some(x) = User::select_by_email(rb, &item.email).await? {
        if x.id != id {
            return Err(AppError::BusinessError("邮箱账号已存在"));
        }
    }

    let post_ids = item.post_ids.clone();
    let mut user_post_list: Vec<UserPost> = Vec::new();
    for post_id in post_ids {
        user_post_list.push(UserPost {
            user_id: user.id.unwrap_or_default(),
            post_id,
        })
    }

    UserPost::delete_by_map(rb, value! {"user_id": &item.id}).await?;
    UserPost::insert_batch(rb, &user_post_list, user_post_list.len() as u64).await?;

    User::update_by_map(rb, &User::from(item), value! {"id": &id}).await.map(|_| ok_result(res))?
}

/*
 *更新用户信息状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_user_status(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<UpdateUserStatusReq>().await?;
    log::info!("update sys_user_status params: {:?}", &item);

    let ids = item.ids.clone();
    if ids.contains(&1) {
        return Err(AppError::BusinessError("不允许操作超级管理员用户"));
    }

    let update_sql = format!(
        "update sys_user set status = ? ,update_time = ? where id in ({})",
        item.ids.iter().map(|_| "?").collect::<Vec<&str>>().join(", ")
    );

    let mut param = vec![value!(item.status), value!(DateTime::now())];
    param.extend(item.ids.iter().map(|&id| value!(id)));

    RB.clone().exec(&update_sql, param).await.map(|_| ok_result(res))?
}

/*
 *重置用户密码
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn reset_sys_user_password(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<ResetUserPwdReq>().await?;
    log::info!("update sys_user_password params: {:?}", &item);

    let id = item.id.clone();
    if id == 1 {
        return Err(AppError::BusinessError("不允许操作超级管理员用户"));
    }

    let rb = &mut RB.clone();

    match User::select_by_id(rb, item.id).await? {
        None => Err(AppError::BusinessError("用户不存在")),
        Some(x) => {
            let mut user = x;
            user.password = item.password;
            User::update_by_map(rb, &user, value! {"id": &user.id}).await.map(|_| ok_result(res))?
        }
    }
}

/*
 *用户修改自己的密码
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_user_password(req: &mut Request, depot: &mut Depot, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<UpdateUserPwdReq>().await?;
    log::info!("update sys_user_password params: {:?}", &item);

    if let Ok(user_id) = depot.get::<i64>("userId").copied() {
        let rb = &mut RB.clone();

        match User::select_by_id(rb, user_id).await? {
            None => Err(AppError::BusinessError("用户不存在")),
            Some(x) => {
                let mut user = x;
                if user.password != item.pwd {
                    return Err(AppError::BusinessError("旧密码不正确"));
                }
                user.password = item.re_pwd;

                User::update_by_map(rb, &user, value! {"id": &user.id}).await.map(|_| ok_result(res))?
            }
        }
    } else {
        Err(AppError::BusinessError("用户ID不能为空"))
    }
}

/*
 *查询用户信息详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_user_detail(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<QueryUserDetailReq>().await?;
    log::info!("query sys_user_detail params: {:?}", &item);

    let rb = &mut RB.clone();

    let mut x = match User::select_by_id(rb, item.id).await? {
        None => return Err(AppError::BusinessError("用户不存在")),
        Some(user) => {
            let a: UserResp = user.into();
            a
        }
    };

    let dept = match Dept::select_by_id(rb, &x.dept_id).await? {
        None => return Err(AppError::BusinessError("部门不存在")),

        Some(y) => {
            let a: DeptResp = y.into();
            Some(a)
        }
    };

    let post_ids = UserPost::select_by_map(rb, value! {"user_id": item.id}).await?.iter().map(|x| x.post_id).collect::<Vec<i64>>();

    x.dept_info = dept;
    x.post_ids = Some(post_ids);

    ok_result_data(res, x)
}

/*
 *查询用户信息列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_user_list(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let req = req.parse_json::<QueryUserListReq>().await?;
    log::info!("query sys_user_list params: {:?}", &req);

    let rb = &mut RB.clone();
    let item = &req;

    User::select_sys_user_list(rb, &PageRequest::from(item), item)
        .await
        .map(|x| ok_result_page(res, x.records.into_iter().map(|x| x.into()).collect::<Vec<UserResp>>(), x.total))?
}

/*
 *用户登录
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn login(depot: &mut Depot, req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<UserLoginReq>().await?;
    log::info!("user login params: {:?}", &item);

    let user_agent = req.header::<&str>("user-agent").unwrap_or_default();
    log::info!("user agent: {:?}", user_agent);
    let agent = UserAgentUtil::new(user_agent);

    let rb = &mut RB.clone();
    let user_result = User::select_by_mobile(rb, &item.mobile).await?;
    log::info!("query user by mobile: {:?}", user_result);

    match user_result {
        None => {
            add_login_log(item.mobile, 0, "用户不存在", agent).await;
            Err(AppError::BusinessError("用户不存在"))
        }
        Some(user) => {
            let mut s_user = user.clone();
            let id = user.id.unwrap_or_default();
            let username = user.user_name;
            let password = user.password;

            if password.ne(&item.password) {
                add_login_log(item.mobile, 0, "密码不正确", agent).await;
                return Err(AppError::BusinessError("密码不正确"));
            }

            let (btn_menu, is_super) = query_btn_menu(&id).await;

            if btn_menu.len() == 0 {
                add_login_log(item.mobile, 0, "用户没有分配角色或者菜单,不能登录", agent).await;
                return Err(AppError::BusinessError("用户没有分配角色或者菜单,不能登录"));
            }

            let secret = depot.get::<String>("secret").map_err(|_| AppError::BusinessError("获取jwt密钥异常"))?;
            let token = JwtToken::new(id, &username).create_token(secret)?;

            let pool = depot.get::<deadpool_redis::Pool>("pool").map_err(|_| AppError::BusinessError("获取redis连接池异常"))?;
            let mut conn = pool.get().await.map_err(|_| AppError::BusinessError("获取redis连接异常"))?;
            let key = format!("salvo:admin:user:info:{:?}", s_user.id.unwrap_or_default());
            deadpool_redis::redis::cmd("HSET")
                .arg(&key)
                .arg(&"permissions")
                .arg(&btn_menu.join(","))
                .arg(&"user_name")
                .arg(&s_user.user_name)
                .arg(&"is_admin")
                .arg(&is_super)
                .arg(&"token")
                .arg(&token)
                .arg(&"last_login")
                .arg(&Local::now().format("%Y-%m-%d %H:%M:%S").to_string())
                .query_async::<()>(&mut conn)
                .await?;

            add_login_log(item.mobile, 1, "登录成功", agent.clone()).await;
            s_user.login_os = agent.os;
            s_user.login_browser = agent.browser;
            s_user.login_date = Some(DateTime::now());

            User::update_by_map(rb, &s_user, value! {"id": &s_user.id}).await?;
            ok_result_data(res, token)
        }
    }
}

/*
 *添加登录日志
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
async fn add_login_log(name: String, status: i8, msg: &str, agent: UserAgentUtil) {
    let sys_login_log = LoginLog {
        id: None,                             //访问ID
        login_name: name,                     //登录账号
        ipaddr: "todo".to_string(),           //登录IP地址
        login_location: "todo".to_string(),   //登录地点
        platform: agent.platform,             //平台信息
        browser: agent.browser,               //浏览器类型
        version: agent.version,               //浏览器版本
        os: agent.os,                         //操作系统
        arch: agent.arch,                     //体系结构信息
        engine: agent.engine,                 //渲染引擎信息
        engine_details: agent.engine_details, //渲染引擎详细信息
        extra: agent.extra,                   //其他信息（可选）
        status,                               //登录状态(0:失败,1:成功)
        msg: msg.to_string(),                 //提示消息
        login_time: None,                     //访问时间
    };

    match LoginLog::insert(&mut RB.clone(), &sys_login_log).await {
        Ok(_u) => log::info!("add_login_log success: {:?}", sys_login_log),
        Err(err) => log::error!("add_login_log error params: {:?}, error message: {:?}", sys_login_log, err),
    }
}

/*
 *查询按钮权限
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
async fn query_btn_menu(id: &i64) -> (Vec<String>, bool) {
    let mut btn_menu: Vec<String> = Vec::new();
    let rb = &mut RB.clone();
    let count = is_admin(rb, id).await.unwrap_or_default();
    if count == 1 {
        for x in Menu::select_all(rb).await.unwrap_or_default() {
            if let Some(a) = x.api_url {
                if a != "" {
                    btn_menu.push(a);
                }
            }
        }

        log::info!("The current user is a super administrator");
        (btn_menu, true)
    } else {
        let sql_str = "select distinct u.api_url from sys_user_role t left join sys_role usr on t.role_id = usr.id left join sys_role_menu srm on usr.id = srm.role_id left join sys_menu u on srm.menu_id = u.id where t.user_id = ?";
        let btn_menu_map = rb.query_decode::<Vec<HashMap<String, String>>>(sql_str, vec![value!(id)]).await.unwrap_or_default();
        for x in btn_menu_map {
            if let Some(a) = x.get("api_url") {
                if a.to_string() != "" {
                    btn_menu.push(a.to_string());
                }
            }
        }
        log::info!("The current user is not a super administrator");
        (btn_menu, false)
    }
}

/*
 *查询用户角色
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_user_role(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<QueryUserRoleReq>().await?;
    log::info!("query_user_role params: {:?}", item);

    let rb = &mut RB.clone();
    let mut user_role_ids: Vec<i64> = Vec::new();

    let user_id = item.user_id;
    for x in UserRole::select_by_map(rb, value! {"user_id": user_id}).await? {
        user_role_ids.push(x.role_id);
    }

    let sys_role_list = Role::select_all(rb).await.map(|x| x.into_iter().map(|x| x.into()).collect::<Vec<RoleResp>>())?;

    ok_result_data(res, QueryUserRoleResp { sys_role_list, user_role_ids })
}

/*
 *更新用户与角色的关联
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_user_role(req: &mut Request, res: &mut Response) -> AppResult<()> {
    let item = req.parse_json::<UpdateUserRoleReq>().await?;
    log::info!("update_user_role params: {:?}", item);

    let user_id = item.user_id.clone();
    let role_ids = &item.role_ids;
    let len = item.role_ids.len();

    if user_id.clone() == 1 {
        return Err(AppError::BusinessError("不能修改超级管理员的角色"));
    }

    let rb = &mut RB.clone();

    UserRole::delete_by_map(rb, value! {"user_id": user_id.clone()}).await?;

    let mut list: Vec<UserRole> = Vec::new();
    for role_id in role_ids {
        let r_id = role_id.clone();
        list.push(UserRole {
            id: None,
            create_time: Some(DateTime::now()),
            role_id: r_id,
            user_id: user_id.clone(),
        })
    }

    UserRole::insert_batch(rb, &list, len as u64).await.map(|_| ok_result(res))?
}

/*
 *查询用户菜单
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_user_menu(depot: &mut Depot, res: &mut Response) -> AppResult<()> {
    log::info!("query user menu params {:?}", depot);
    let user_id = depot.get::<i64>("userId").copied().unwrap();
    let user_name = depot.get::<String>("username").unwrap();
    log::info!("query user menu params user_id {:?}", user_id);
    log::info!("query user menu params user_name {:?}", user_name);

    //根据id查询用户
    let rb = &mut RB.clone();

    match User::select_by_id(rb, user_id).await? {
        None => Err(AppError::BusinessError("用户不存在")),
        Some(user) => {
            //role_id为1是超级管理员--判断是不是超级管理员
            let count = is_admin(rb, &user_id).await?;

            let sys_menu_list: Vec<Menu>;

            if count == 1 {
                log::info!("The current user is a super administrator");
                sys_menu_list = Menu::select_all(rb).await?;
            } else {
                log::info!("The current user is not a super administrator");
                let sql_str = "select u.* from sys_user_role t left join sys_role usr on t.role_id = usr.id left join sys_role_menu srm on usr.id = srm.role_id left join sys_menu u on srm.menu_id = u.id where t.user_id = ?";
                sys_menu_list = RB.query_decode(sql_str, vec![value!(user.id)]).await?;
            }

            let mut sys_menu: Vec<MenuList> = Vec::new();
            let mut btn_menu: Vec<String> = Vec::new();
            let mut sys_menu_ids: HashSet<i64> = HashSet::new();

            for x in sys_menu_list {
                if x.menu_type != 3 {
                    sys_menu_ids.insert(x.id.unwrap_or_default());
                    sys_menu_ids.insert(x.parent_id.unwrap_or_default().clone());
                }
                if x.api_url.clone().unwrap_or_default().len() > 0 {
                    btn_menu.push(x.api_url.unwrap_or_default());
                }
            }

            let mut menu_ids = Vec::new();
            for id in sys_menu_ids {
                menu_ids.push(id)
            }
            for menu in Menu::select_by_ids(rb, &menu_ids).await? {
                let api_url = menu.api_url.unwrap_or_default();
                sys_menu.push(MenuList {
                    id: menu.id,
                    parent_id: menu.parent_id,
                    name: menu.menu_name,
                    icon: menu.menu_icon.unwrap_or_default(),
                    api_url: api_url.clone(),
                    menu_type: menu.menu_type,
                    path: menu.menu_url.unwrap_or_default(),
                });

                if api_url.len() > 0 {
                    btn_menu.push(api_url);
                }
            }

            ok_result_data(
                res,
                QueryUserMenuResp {
                    sys_menu,
                    btn_menu,
                    avatar: "https://gw.alipayobjects.com/zos/antfincdn/XAosXuNZyF/BiazfanxmamNRoxxVxka.png".to_string(),
                    name: user.user_name,
                },
            )
        }
    }
}
