// Code generated by https://github.com/feihua/code_cli
// author：刘飞华
// date：2025/01/08 13:51:14

use crate::common::error::{AppResult, AppResultPage};
use crate::service::system::sys_role_service::RoleService;
use crate::vo::system::sys_role_vo::*;
use crate::vo::system::sys_user_vo::UserResp;
use salvo::oapi::extract::JsonBody;
use salvo::prelude::*;
use tracing::info;
/*
 *添加角色信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn add_sys_role(req: JsonBody<RoleReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("add sys_role params: {:?}", &item);

    RoleService::add_sys_role(item).await
}

/*
 *删除角色信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn delete_sys_role(req: JsonBody<DeleteRoleReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("delete sys_role params: {:?}", &item);

    RoleService::delete_sys_role(item).await
}

/*
 *更新角色信息
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_role(req: JsonBody<RoleReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("update sys_role params: {:?}", &item);

    RoleService::update_sys_role(item).await
}

/*
 *更新角色信息状态
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_sys_role_status(req: JsonBody<UpdateRoleStatusReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("update sys_role_status params: {:?}", &item);

    RoleService::update_sys_role_status(item).await
}

/*
 *查询角色信息详情
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_role_detail(req: JsonBody<QueryRoleDetailReq>) -> AppResult<RoleResp> {
    let item = req.into_inner();
    info!("query sys_role_detail params: {:?}", &item);

    RoleService::query_sys_role_detail(item).await
}

/*
 *查询角色信息列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_sys_role_list(req: JsonBody<QueryRoleListReq>) -> AppResultPage<RoleResp> {
    let item = req.into_inner();
    info!("query sys_role_list params: {:?}", &item);

    RoleService::query_sys_role_list(item).await
}

/*
 *查询角色关联的菜单
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_role_menu(req: JsonBody<QueryRoleMenuReq>) -> AppResult<QueryRoleMenuData> {
    let item = req.into_inner();
    info!("query role_menu params: {:?}", &item);

    RoleService::query_role_menu(item).await
}

/*
 *更新角色关联的菜单
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn update_role_menu(req: JsonBody<UpdateRoleMenuReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("update_role_menu params: {:?}", &item);

    RoleService::update_role_menu(item).await
}

/*
 *查询已分配用户角色列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_allocated_list(req: JsonBody<AllocatedListReq>) -> AppResultPage<UserResp> {
    let item = req.into_inner();
    info!("update role_menu params: {:?}", &item);

    RoleService::query_allocated_list(item).await
}

/*
 *查询未分配用户角色列表
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn query_unallocated_list(req: JsonBody<UnallocatedListReq>) -> AppResultPage<UserResp> {
    let item = req.into_inner();
    info!("update role_menu params: {:?}", &item);

    RoleService::query_unallocated_list(item).await
}

/*
 *取消授权用户
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn cancel_auth_user(req: JsonBody<CancelAuthUserReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("update role_menu params: {:?}", &item);

    RoleService::cancel_auth_user(item).await
}

/*
 *批量取消授权用户
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn batch_cancel_auth_user(req: JsonBody<CancelAuthUserAllReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("cancel auth_user_all params: {:?}", &item);

    RoleService::batch_cancel_auth_user(item).await
}

/*
 *批量选择用户授权
 *author：刘飞华
 *date：2025/01/08 13:51:14
 */
#[handler]
pub async fn batch_auth_user(req: JsonBody<SelectAuthUserAllReq>) -> AppResult<String> {
    let item = req.into_inner();
    info!("select all_auth_user params: {:?}", &item);

    RoleService::batch_auth_user(item).await
}
